package systemd_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/wighawag/anonctl/internal/systemd"
)

// hostOwnedStore returns a scratch store in host-owned mode, with the two units
// declared in a separate "host" directory that outranks anonctl's own, plus the
// marker. It mirrors the real shape: on NixOS a declared unit renders into
// /etc/systemd/system, which systemd ranks ABOVE /usr/local/lib/systemd/system.
//
// The declared units are produced by the REAL exporter, pointed at this store's own
// directories, which is exactly what a correctly configured host has. That makes the
// fixture double as the tie between the preflight's agreement check and the
// generators it mirrors: if TemplateUnit's EnvironmentFile line or InstallCommon's
// rules glob ever changed shape, every test built on this fixture would fail.
func hostOwnedStore(t *testing.T) (systemd.Store, string) {
	t.Helper()
	s := scratchStore(t)
	root := filepath.Dir(s.UnitDir)
	hostDir := filepath.Join(root, "host-systemd")
	marker := filepath.Join(root, "units.host-owned")
	if err := os.WriteFile(marker, nil, 0o644); err != nil {
		t.Fatalf("write marker: %v", err)
	}
	s.HostOwnedMarker = marker
	s.SearchDirs = []string{hostDir, s.UnitDir}
	declareHostUnits(t, s, hostDir)
	return s, hostDir
}

// declareHostUnits writes the two units a host would declare into dir, generated by
// the real exporter against this store's directories and against binaries that
// really exist (the preflight checks both).
func declareHostUnits(t *testing.T, s systemd.Store, dir string) {
	t.Helper()
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	bin := filepath.Join(filepath.Dir(s.UnitDir), "store-bin")
	if err := os.MkdirAll(bin, 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	paths := map[string]string{}
	for _, name := range []string{"setpriv", "anonctl-shim", "nft"} {
		p := filepath.Join(bin, name)
		if err := os.WriteFile(p, []byte("#!/bin/sh\n"), 0o755); err != nil {
			t.Fatalf("write fake %s: %v", name, err)
		}
		paths[name] = p
	}
	shim, err := systemd.Export(systemd.ExportParams{
		Kind:           systemd.KindShim,
		SetprivPath:    paths["setpriv"],
		ShimBinaryPath: paths["anonctl-shim"],
		EnvDir:         s.EnvDir,
	})
	if err != nil {
		t.Fatalf("export shim: %v", err)
	}
	loader, err := systemd.Export(systemd.ExportParams{
		Kind:     systemd.KindNftables,
		NftPath:  paths["nft"],
		RulesDir: s.RulesDir,
	})
	if err != nil {
		t.Fatalf("export loader: %v", err)
	}
	for name, text := range map[string]string{systemd.UnitName: shim, systemd.LoaderUnitName: loader} {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(text), 0o644); err != nil {
			t.Fatalf("write host unit %s: %v", name, err)
		}
	}
}

// A correctly declared host passes the preflight. This is the fixture's other job:
// it ties the preflight's agreement check to the generators it mirrors, so a change
// to either one that broke the agreement fails here rather than at a host's next
// boot.
func TestPreflightAcceptsUnitsExportedForThisStore(t *testing.T) {
	s, hostDir := hostOwnedStore(t)
	found, err := s.PreflightHostUnits()
	if err != nil {
		t.Fatalf("PreflightHostUnits rejected units exported for this very store: %v", err)
	}
	for _, name := range systemd.SharedUnitNames() {
		if found[name] != filepath.Join(hostDir, name) {
			t.Errorf("preflight resolved %s to %q, want the declared copy in %q", name, found[name], hostDir)
		}
	}
}

// THE SILENT FAIL-OPEN, and the reason the preflight checks more than "the file
// exists". A loader that globs the wrong directory loads NOTHING at boot: no
// forcing, and no standing baseline default-deny, so the account egresses directly
// with the host's real IP. Nothing else catches it -- anonctl pins that glob itself
// when it owns the unit, the glob is not a binary so the binary check skips it, the
// loader is enabled-but-not-started so the mistake is never exercised before the
// boot it breaks, and `verify` reports green because the LIVE rules are correct.
func TestPreflightRefusesALoaderThatGlobsTheWrongRulesDir(t *testing.T) {
	s, hostDir := hostOwnedStore(t)
	wrong, err := systemd.Export(systemd.ExportParams{
		Kind:     systemd.KindNftables,
		NftPath:  filepath.Join(filepath.Dir(s.UnitDir), "store-bin", "nft"),
		RulesDir: "/etc/anonctl/rules", // plausible, and NOT where anonctl writes
	})
	if err != nil {
		t.Fatalf("export: %v", err)
	}
	if err := os.WriteFile(filepath.Join(hostDir, systemd.LoaderUnitName), []byte(wrong), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}
	_, err = s.PreflightHostUnits()
	if err == nil {
		t.Fatal("a declared loader globbing the WRONG directory was accepted: at the next boot it would load no baseline default-deny at all, and the account would egress with the host's real IP")
	}
	for _, want := range []string{"/etc/anonctl/rules", s.RulesDir, "real IP"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("the refusal must name %q so the operator can fix it; got: %v", want, err)
		}
	}
}

// The same class, one step earlier: a packaged `.in` file installed with some tokens
// left unsubstituted. In the shim that is loud (the instance fails to start); in the
// loader it is silent and fail-open, so both are refused by one check rather than
// leaving an operator to learn which is which.
func TestPreflightRefusesAnUnsubstitutedPlaceholder(t *testing.T) {
	for _, name := range systemd.SharedUnitNames() {
		s, hostDir := hostOwnedStore(t)
		kind := systemd.KindShim
		if name == systemd.LoaderUnitName {
			kind = systemd.KindNftables
		}
		raw, err := systemd.ExportPlaceholders(kind)
		if err != nil {
			t.Fatalf("ExportPlaceholders: %v", err)
		}
		if err := os.WriteFile(filepath.Join(hostDir, name), []byte(raw), 0o644); err != nil {
			t.Fatalf("write: %v", err)
		}
		_, perr := s.PreflightHostUnits()
		if perr == nil {
			t.Errorf("%s was accepted with its @name@ placeholders still in place", name)
			continue
		}
		if !strings.Contains(perr.Error(), "placeholder") {
			t.Errorf("the refusal for %s does not explain that a token was left unsubstituted: %v", name, perr)
		}
	}
}

// A declared shim that reads its EnvironmentFile from the wrong directory is
// fail-CLOSED (the instance does not start, the baseline still drops) but it is
// still an account that silently never comes up, so it is refused at install time
// like its fail-open sibling.
func TestPreflightRefusesAShimReadingTheWrongEnvDir(t *testing.T) {
	s, hostDir := hostOwnedStore(t)
	bin := filepath.Join(filepath.Dir(s.UnitDir), "store-bin")
	wrong, err := systemd.Export(systemd.ExportParams{
		Kind:           systemd.KindShim,
		SetprivPath:    filepath.Join(bin, "setpriv"),
		ShimBinaryPath: filepath.Join(bin, "anonctl-shim"),
		EnvDir:         "/etc/anonctl/env",
	})
	if err != nil {
		t.Fatalf("export: %v", err)
	}
	if err := os.WriteFile(filepath.Join(hostDir, systemd.UnitName), []byte(wrong), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}
	if _, err := s.PreflightHostUnits(); err == nil {
		t.Fatal("a declared shim reading the wrong env dir was accepted: every account's shim would start with no endpoint, no uid and no ports")
	}
}

// THE ONE THE BINARY SWEEP CANNOT SEE. The loader's generated ExecStart starts with
// an absolute `/bin/sh`, so the "did every absolute path exist" check is satisfied by
// that alone, and a BARE `nft` after the `&&` sails through it: at boot the unit
// inherits no useful $PATH, exits 127, and loads nothing at all -- no forcing and no
// standing baseline default-deny, so the account egresses with the host's real IP,
// silently, and only after a reboot.
//
// `--nft nft` is a natural thing to write for anyone with a working shell, so it is
// refused at both ends: the emitter will not produce it (TestUnitsPrintRefusesA
// RelativeBinaryPath) and the preflight will not accept it if it arrives by another
// route.
func TestPreflightRefusesALoaderWhoseNftIsNotAbsolute(t *testing.T) {
	s, hostDir := hostOwnedStore(t)
	// The right glob, an existing /bin/sh, and a bare `nft`: everything the other
	// checks look at is correct.
	text := "[Unit]\nDescription=relative nft\n[Service]\nType=oneshot\nExecStart=/bin/sh -c 'for f in " +
		filepath.Join(s.RulesDir, "*.nft") + "; do [ -e \"$f\" ] && nft -f \"$f\"; done'\n"
	if err := os.WriteFile(filepath.Join(hostDir, systemd.LoaderUnitName), []byte(text), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}
	_, err := s.PreflightHostUnits()
	if err == nil {
		t.Fatal("a declared loader running a BARE `nft` was accepted: at boot that is exit 127, no rules loaded, no standing default-deny, and real-IP egress")
	}
	for _, want := range []string{"nft", "127", "real IP"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("the refusal must mention %q; got: %v", want, err)
		}
	}
}

// A unit whose ExecStart anonctl cannot parse at all is refused rather than waved
// through: "I could not check this" must never read as "this is fine", which is the
// rule verify already applies to the same files.
func TestPreflightRefusesUnitsItCannotReadABinaryOutOf(t *testing.T) {
	s, hostDir := hostOwnedStore(t)
	// Both units hand-written: the couplings anonctl checks are correct (right env dir,
	// right rules glob), but every binary is named RELATIVELY, so nothing absolute can
	// be parsed out and "what will this exec" is simply unknown.
	units := map[string]string{
		systemd.UnitName: "[Unit]\nDescription=hand-written shim\n[Service]\nEnvironmentFile=" + s.EnvDir +
			"/%i.env\nExecStart=setpriv --reuid ${ANONCTL_SHIM_UID} anonctl-shim\n",
		systemd.LoaderUnitName: "[Unit]\nDescription=hand-written loader\n[Service]\nType=oneshot\nExecStart=sh -c 'for f in " +
			filepath.Join(s.RulesDir, "*.nft") + "; do nft -f \"$f\"; done'\n",
	}
	for name, text := range units {
		if err := os.WriteFile(filepath.Join(hostDir, name), []byte(text), 0o644); err != nil {
			t.Fatalf("write %s: %v", name, err)
		}
	}
	_, err := s.PreflightHostUnits()
	if err == nil {
		t.Fatal("units yielding NO checkable binary were accepted: `verify` refuses exactly this input, so install-time green and verify-time red would disagree about one unchanged host")
	}
	// It must name the unit it could not vouch for. The precise reason is allowed to be
	// the sharper one (the loader's command is not absolute), which is what this input
	// now trips first.
	if !strings.Contains(err.Error(), systemd.LoaderUnitName) {
		t.Errorf("the refusal does not name the unit it could not vouch for: %v", err)
	}
}

// A store with NO marker behaves precisely as it always has: both unit files are
// written. This is the "a host that says nothing is unaffected" guarantee, asserted
// rather than assumed, because every other test in this file changes that behaviour.
func TestWithoutTheMarkerInstallCommonStillWritesBothUnits(t *testing.T) {
	s := scratchStore(t)
	tp, lp := scratchParams()
	if err := s.InstallCommon(tp, lp); err != nil {
		t.Fatalf("InstallCommon: %v", err)
	}
	for _, name := range systemd.SharedUnitNames() {
		if _, err := os.Stat(filepath.Join(s.UnitDir, name)); err != nil {
			t.Errorf("a store with no host-owned marker did not write %s: %v", name, err)
		}
	}
	own, err := s.UnitOwnership()
	if err != nil {
		t.Fatalf("UnitOwnership: %v", err)
	}
	if own.HostOwned {
		t.Error("a store with no marker reported the units as host-owned")
	}
}

// InstallCommon is the MECHANISM, and it refuses to write in host-owned mode on its
// own: the guard lives with the write rather than only in the orchestration that
// calls it, so a future caller cannot reintroduce the second definition by calling
// this directly.
func TestInstallCommonWritesNothingWhenTheHostOwnsTheUnits(t *testing.T) {
	s, hostDir := hostOwnedStore(t)
	before := declaredContents(t, hostDir)
	// Not even resolved params: in this mode the caller is not required to have them,
	// because nothing is generated.
	if err := s.InstallCommon(systemd.TemplateParams{}, systemd.LoaderParams{}); err != nil {
		t.Fatalf("InstallCommon in host-owned mode: %v", err)
	}
	for _, name := range systemd.SharedUnitNames() {
		if _, err := os.Stat(filepath.Join(s.UnitDir, name)); !os.IsNotExist(err) {
			t.Errorf("InstallCommon wrote %s although the host owns the units", name)
		}
		if after := readFile(t, filepath.Join(hostDir, name)); after != before[name] {
			t.Errorf("InstallCommon REWROTE the host-declared %s", name)
		}
	}
}

// readFile is a fatal-on-error read, for before/after content comparisons.
func readFile(t *testing.T, path string) string {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	return string(b)
}

// declaredContents snapshots the declared unit files, so a test can prove they were
// not touched rather than merely that they still exist.
func declaredContents(t *testing.T, dir string) map[string]string {
	t.Helper()
	out := map[string]string{}
	for _, name := range systemd.SharedUnitNames() {
		out[name] = readFile(t, filepath.Join(dir, name))
	}
	return out
}

// RemoveCommon is the teardown counterpart, and the single most dangerous
// interaction in this feature: the last account's cleanup deletes the shared units,
// and in host-owned mode that would delete part of the host's declared
// configuration.
func TestRemoveCommonStillCleansAnonctlsOwnArtifactsInHostOwnedMode(t *testing.T) {
	s, hostDir := hostOwnedStore(t)
	before := declaredContents(t, hostDir)
	// Both an enablement symlink (anonctl's, must go) and the declared units (the
	// host's, must stay).
	if err := s.EnableUnit(systemd.LoaderUnitName, systemd.LoaderUnitName, systemd.LoaderWantedBy); err != nil {
		t.Fatalf("EnableUnit: %v", err)
	}
	if err := s.RemoveCommon(); err != nil {
		t.Fatalf("RemoveCommon: %v", err)
	}
	for _, name := range systemd.SharedUnitNames() {
		if after := readFile(t, filepath.Join(hostDir, name)); after != before[name] {
			t.Errorf("RemoveCommon disturbed the host-declared %s", name)
		}
	}
	link := filepath.Join(s.UnitDir, systemd.LoaderWantedBy+".wants", systemd.LoaderUnitName)
	if _, err := os.Lstat(link); !os.IsNotExist(err) {
		t.Errorf("RemoveCommon left anonctl's own enablement symlink %s behind: host ownership of the unit FILES is not ownership of the symlinks", link)
	}
}

// THE CASE THE GUARD ACTUALLY EXISTS FOR: the host declares the units straight INTO
// anonctl's own unit dir. Nothing stops it -- /usr/local/lib/systemd/system is an
// ordinary directory, and a host that is not NixOS may well put its files there --
// and then the paths RemoveCommon deletes ARE the host's files.
//
// Without this case the guard is untestable by construction: every other fixture
// puts the declared units in a different directory, so the deletion misses them and
// the test passes even with the guard removed. Verified: deleting the `if
// !own.HostOwned` guard leaves the other teardown tests green and fails only this
// one.
func TestRemoveCommonNeverDeletesHostUnitsDeclaredInAnonctlsOwnUnitDir(t *testing.T) {
	s := scratchStore(t)
	marker := filepath.Join(filepath.Dir(s.UnitDir), "units.host-owned")
	if err := os.WriteFile(marker, nil, 0o644); err != nil {
		t.Fatalf("write marker: %v", err)
	}
	s.HostOwnedMarker = marker
	s.SearchDirs = []string{s.UnitDir}
	// The host declares them exactly where anonctl would have written its own.
	declareHostUnits(t, s, s.UnitDir)
	before := declaredContents(t, s.UnitDir)

	if _, err := s.PreflightHostUnits(); err != nil {
		t.Fatalf("PreflightHostUnits: %v", err)
	}
	if err := s.RemoveCommon(); err != nil {
		t.Fatalf("RemoveCommon: %v", err)
	}
	for _, name := range systemd.SharedUnitNames() {
		path := filepath.Join(s.UnitDir, name)
		if _, err := os.Stat(path); err != nil {
			t.Fatalf("the last account's teardown DELETED %s, which the host declares: %v", path, err)
		}
		if after := readFile(t, path); after != before[name] {
			t.Errorf("the teardown rewrote the host-declared %s", name)
		}
	}
}

// The legacy sweep deletes anonctl units from /etc/systemd/system because a leftover
// there SHADOWS the current one. In host-owned mode that same directory is where a
// declarative host puts the units it declares, and anonctl cannot tell the two apart
// by path. The two mistakes are not symmetric -- residue is inert, a deleted
// declaration is a unit that is simply GONE at the next boot -- so the sweep is
// skipped.
func TestMigrateLegacyUnitsIsSkippedWhenTheHostOwnsTheUnits(t *testing.T) {
	s, _ := hostOwnedStore(t)
	// Point the legacy dir at the very place a NixOS host declares its units, and put
	// a declaration there.
	legacy := filepath.Join(filepath.Dir(s.UnitDir), "etc-systemd-system")
	if err := os.MkdirAll(legacy, 0o755); err != nil {
		t.Fatalf("mkdir legacy: %v", err)
	}
	declared := filepath.Join(legacy, systemd.LoaderUnitName)
	if err := os.WriteFile(declared, []byte("[Unit]\nDescription=declared by the host\n"), 0o644); err != nil {
		t.Fatalf("write declared unit: %v", err)
	}
	s.LegacyUnitDir = legacy
	removed, err := s.MigrateLegacyUnits()
	if err != nil {
		t.Fatalf("MigrateLegacyUnits: %v", err)
	}
	if len(removed) != 0 {
		t.Errorf("the legacy sweep removed %v in host-owned mode; it must not touch that directory, because it is where a declarative host puts the units it declares", removed)
	}
	if _, err := os.Stat(declared); err != nil {
		t.Fatalf("the legacy sweep DELETED a host-declared unit: %v", err)
	}
}

// verify's unit-binaries-present assertion reads the unit files to see what the NEXT
// boot will exec. In host-owned mode anonctl's unit dir holds no unit files at all,
// so without this the assertion would report "no anonctl unit could be read" on a
// correctly configured host -- and, worse, would stop checking the binaries the
// host's units actually name, which is exactly where a moved or garbage-collected
// path shows up.
func TestBakedBinariesReadsTheHostsUnitsWhenTheHostOwnsThem(t *testing.T) {
	s, hostDir := hostOwnedStore(t)
	text, err := systemd.Export(systemd.ExportParams{
		Kind:     systemd.KindNftables,
		NftPath:  "/nix/store/aaaa-nftables-1.1.6/bin/nft",
		RulesDir: s.RulesDir,
	})
	if err != nil {
		t.Fatalf("Export: %v", err)
	}
	if err := os.WriteFile(filepath.Join(hostDir, systemd.LoaderUnitName), []byte(text), 0o644); err != nil {
		t.Fatalf("write host loader: %v", err)
	}
	baked, err := s.BakedBinaries()
	if err != nil {
		t.Fatalf("BakedBinaries: %v", err)
	}
	var sawNft bool
	for _, b := range baked {
		if b == "/nix/store/aaaa-nftables-1.1.6/bin/nft" {
			sawNft = true
		}
	}
	if !sawNft {
		t.Errorf("BakedBinaries did not read the host-declared loader; got %v. verify would report that no unit could be read on a correctly configured host", baked)
	}
}

// The shadowing hazard, DETECTED. Two copies of one unit name produce no systemd
// diagnostic at all (measured on systemd 260): the higher-precedence directory wins
// and anonctl's copy sits there looking authoritative while `update` re-bakes a file
// nothing loads.
func TestShadowedUnitsReportsAnonctlsCopyBeingOutranked(t *testing.T) {
	s, hostDir := hostOwnedStore(t)
	// anonctl's own copy is present too (a host that adopted the marker without
	// removing what an earlier `add` wrote).
	if err := os.MkdirAll(s.UnitDir, 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	ours := filepath.Join(s.UnitDir, systemd.LoaderUnitName)
	if err := os.WriteFile(ours, []byte("[Unit]\nDescription=anonctl's own\n"), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}
	shadowed, err := s.ShadowedUnits()
	if err != nil {
		t.Fatalf("ShadowedUnits: %v", err)
	}
	if len(shadowed) != 1 || shadowed[0].Name != systemd.LoaderUnitName {
		t.Fatalf("expected the loader to be reported as shadowed, got %+v", shadowed)
	}
	if shadowed[0].Loaded != filepath.Join(hostDir, systemd.LoaderUnitName) || shadowed[0].Ours != ours {
		t.Errorf("shadow report names the wrong files: %+v", shadowed[0])
	}
	// And it is a REPORT: nothing was deleted, in either direction.
	for _, p := range []string{ours, filepath.Join(hostDir, systemd.LoaderUnitName)} {
		if _, err := os.Stat(p); err != nil {
			t.Errorf("ShadowedUnits deleted %s; it must only report", p)
		}
	}
}

// The unit dir must be writable in EVERY mode, because the per-account enablement
// symlink is anonctl's in every mode. An account that cannot be enabled is an
// account whose forcing silently does not come back after a reboot, so this is
// refused up front rather than discovered after the account exists.
func TestPreflightUnitDirWritableRefusesAReadOnlyUnitDir(t *testing.T) {
	if os.Geteuid() == 0 {
		t.Skip("root bypasses the mode bits this test relies on")
	}
	s, _ := hostOwnedStore(t)
	if err := os.MkdirAll(s.UnitDir, 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	if err := s.PreflightUnitDirWritable(); err != nil {
		t.Fatalf("a writable unit dir was refused: %v", err)
	}
	if err := os.Chmod(s.UnitDir, 0o555); err != nil {
		t.Fatalf("chmod: %v", err)
	}
	t.Cleanup(func() { _ = os.Chmod(s.UnitDir, 0o755) })
	err := s.PreflightUnitDirWritable()
	if err == nil {
		t.Fatal("a read-only unit dir was accepted: anonctl would create the account, apply live rules, and only then fail to write the enablement symlink that makes the forcing survive a reboot")
	}
	if !strings.Contains(err.Error(), "enablement symlink") {
		t.Errorf("the refusal does not explain WHY the dir is needed in host-owned mode: %v", err)
	}
}

// An unreadable marker is an ERROR, never a shrug. Guessing "anonctl owns them" is
// the guess that makes `rm` delete a file the host declares.
func TestAnUnreadableMarkerIsNotTreatedAsAbsent(t *testing.T) {
	if os.Geteuid() == 0 {
		t.Skip("root bypasses the mode bits this test relies on")
	}
	s := scratchStore(t)
	dir := filepath.Join(filepath.Dir(s.UnitDir), "locked")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "units.host-owned"), nil, 0o644); err != nil {
		t.Fatalf("write marker: %v", err)
	}
	if err := os.Chmod(dir, 0o000); err != nil {
		t.Fatalf("chmod: %v", err)
	}
	t.Cleanup(func() { _ = os.Chmod(dir, 0o755) })
	s.HostOwnedMarker = filepath.Join(dir, "units.host-owned")
	if _, err := s.UnitOwnership(); err == nil {
		t.Fatal("an unreadable marker was reported as absent; that guess is what lets rm delete a host-declared unit")
	}
}

// A scratch store (every dir repointed at a temp dir) must never consult the HOST's
// real /etc/anonctl marker: a developer running `go test` on a box that declares its
// units would otherwise run this package's tests in a different mode than they think.
func TestAScratchStoreNeverReadsTheHostsRealMarker(t *testing.T) {
	s := scratchStore(t) // no explicit HostOwnedMarker
	own, err := s.UnitOwnership()
	if err != nil {
		t.Fatalf("UnitOwnership: %v", err)
	}
	if own.MarkerPath != "" {
		t.Errorf("a scratch store resolved a marker path (%q); it must resolve none, or a test on a host-owned box silently changes mode", own.MarkerPath)
	}
	if own.HostOwned {
		t.Error("a scratch store reported host-owned units")
	}
}
